//@ts-nocheck
import Button from "@/components/Button";
import CollapsibleTable from "@/components/CollapsibleTable";
import Head from "next/head";
import CrossIcon from "@public/images/icons/cross.svg";
import FilterIcon from "@public/images/icons/filter.svg";
import Tags from "@/components/Tags";
import Chart from "react-google-charts";
import AreaChart from "@/components/AreaChart";
import mock from "@/mock.json";
const data = [
  ["Месяц", "Деньги", "Траты"],
  ["Июнь", 100000, 42300],
  ["Июль", 117120, 121260],
  ["Август", 66320, 11250],
  ["Сентябрь", 101230, 54120],
];

const options = {
  title: "Эффективность компании",
  hAxis: { title: "Месяц", titleTextStyle: { color: "#333" } },
  vAxis: { minValue: 0, title: "Рубли" },
};
const inside = (
  <div className="flex flex-col">
    <AreaChart data={data} options={options} />
    <Button href="#" className="self-end mb-4 w-fit">
      Подробнее
    </Button>
  </div>
);
const companies = [
  {
    ИНН: 1262662,
    Статус: "Надежный",
    Рейтинг: "5",
    "Будущий рейтинг": "9",
    inside,
  },
  {
    ИНН: 12626262,
    Статус: "Ненадежный",
    Рейтинг: "4",
    futureRating: "7",
    inside,
  },
  {
    ИНН: 12621662,
    Статус: "Надежный",
    Рейтинг: "3",
    "Будущий рейтинг": "1",
    inside,
  },
];
export default function Home() {
  mock.forEach((obj) => (obj.inside = inside));
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full p-4 mt-8 text-3xl ">
        <h2 className="mb-4">Общий рейтинг</h2>
        <div className="relative flex items-center w-full bg-white border rounded-t-lg ">
          <CrossIcon className="absolute left-6 hover:cursor-pointer " />
          <input
            type="text"
            placeholder="ИНН"
            className="flex-1 w-full p-2 pl-12 rounded-t-lg"
          />
          <FilterIcon className="absolute right-40 hover:cursor-pointer " />
          <Button type={"light"} className="absolute px-12 py-2 right-2">
            Найти
          </Button>
        </div>
        <Tags tagsList={["Площадка: АО «ЕЭТП»", "Секция: 44-ФЗ"]} />
        <div>
          <CollapsibleTable headers={Object.keys(mock[0])} rows={mock} />
        </div>
      </main>
    </>
  );
}

